name 'wiwproject'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures wiwproject'
long_description 'Installs/Configures wiwproject'
version '0.1.0'
issues_url 'https://example.com'
source_url 'https://example.com'
depends 'nginx'
depends 'mysql'
